apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanto-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: kanto-ui
  template:
    metadata:
      labels:
        app: kanto-ui
    spec:
      containers:
        - image: pokeapi:0.1
          name: kanto-ui
          ports:
            - containerPort: 3000
          env:
            - name : POKEDEX_NAME
              valueFrom:
                configMapKeyRef:
                  key: POKEDEX_NAME
                  name: kanto-cm
            - name: POKEDEX_START_NUMBER
              valueFrom:
                configMapKeyRef:
                  key: POKEDEX_START_NUMBER
                  name: kanto-cm
            - name: POKEDEX_END_NUMBER
              valueFrom:
                configMapKeyRef:
                  key: POKEDEX_END_NUMBER
                  name: kanto-cm
