apiVersion: apps/v1
kind: Deployment
metadata:
  name: joto-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: joto-ui
  template:
    metadata:
      labels:
        app: joto-ui
    spec:
      containers:
        - image: pokeapi:0.1
          name: joto-ui
          ports:
            - containerPort: 3000
          env:
              - name: POKEDEX_NAME
                valueFrom:
                  configMapKeyRef:
                    key: POKEDEX_NAME
                    name: joto-cm
              - name: POKEDEX_START_NUMBER
                valueFrom:
                  configMapKeyRef:
                    key: POKEDEX_START_NUMBER
                    name: joto-cm
              - name: POKEDEX_END_NUMBER
                valueFrom:
                  configMapKeyRef:
                    key: POKEDEX_END_NUMBER
                    name: joto-cm
